[[XSession]]
src = 'Xdefaults'
type = 'dotfile'

[[XSession]]
src = 'xinitrc'
type = 'dotfile'

[[Mercurial]]
src = 'hgrc'
type = 'dotfile'

[[Git]]
src = 'gitconfig'
type = 'dotfile'

[[NVim]]
src = 'nvim' # default 

[[Zsh]]
repo = 'https://github.com/robbyrussell/oh-my-zsh.git'
dest = '~/.oh-my-zsh'

[[Zsh]]
src = 'zshrc'
type = 'dotfile'

[[MPV]]
src = 'mpv'

[[TMux]]
src = 'tmux'

[[Hypr]]
src = 'hypr'

[[Waybar]]
src = 'waybar'

[[Wezterm]]
src = 'wezterm'

[[Mako]]
src = 'mako'
